# Generated by Django 5.2.3 on 2025-06-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-rating', '-price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='request_query',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Поисковый запрос'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Название товара', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'supplier', 'request_query')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='products_pr_title_7d8124_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['request_query'], name='products_pr_request_5e1425_idx'),
        ),
    ]
